## Unistore config template
##  Human-readable big numbers:
##   Time(based on ms): ms, s, m, h
##    e.g.: 78_000 = "1.3m"
##  TODO
##   File size(based on byte): KB, MB, GB, TB, PB
##    e.g.: 1_048_576 = "1MB"

## PD server address
pd-addr = "127.0.0.1:2379"

## Unistore server address
store-addr = "127.0.0.1:20160"

## Log levels: trace, debug, info, warning, error, critical.
## Note that `debug` and `trace` are only available in development builds.
log-level = "info"

## Raft store enabled or not
raft = true

## Path for db storage
db-path = "/tmp/badger"